name: Build and Deploy Resume

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -jobname=resume

      - name: Upload LaTeX artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: resume.pdf

  commit-output:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: PDF

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: Add and commit changes
        run: |
          mv resume.pdf $GITHUB_WORKSPACE/output/resume.pdf
          git config --global user.name 'workflow-bot'
          git config --global user.email 'bot@subhendu17620.github.io'
          git add output/resume.pdf
          git commit -m "[Bot] Update output/resume.pdf"
          git push
  # create-release:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - name: Download PDF artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: PDF
  #     - name: Display structure of downloaded files
  #       run: ls -R
  #     - name: Create release with PDF
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         files: resume.pdf
  #         fail_on_unmatched_files: true
  #         tag_name: "v${{ github.run_number }}"
  #         token: ${{ secrets.GITHUB_TOKEN }}
