name: Build Latex document

# Controls when the action will run.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  create:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: document.pdf
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v3
        with:
          name: PDF
      - name: Create release with PDF
        uses: softprops/action-gh-release@v1
        with:
          files: document.pdf
          fail_on_unmatched_files: true
