name: Build Latex document

# Controls when the action will run.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  create:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true

      - name: Display output of build
        run: ls -R

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: draft.pdf
          path: main.pdf

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: main.pdf
          tag_name: auto_build_draft
          name: Auto build draft
